- name: Download cri-dockerd .deb package
  get_url:
    url: https://github.com/Mirantis/cri-dockerd/releases/download/v0.3.17/cri-dockerd_0.3.17.3-0.debian-bookworm_amd64.deb
    dest: /tmp/cri-dockerd.deb
    mode: '0644'

- name: Install cri-dockerd package
  apt:
    deb: /tmp/cri-dockerd.deb
  register: cri_docker_install

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Enable and start cri-docker service
  systemd:
    name: cri-docker.service
    enabled: yes
    state: started
